/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import config.Koneksi;
import java.sql.Connection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alban
 */
public class FrmTransaksi extends javax.swing.JFrame {
    private Connection koneksi;
    DefaultTableModel model;
    /**
     * Creates new form FrmTransaksi
     */
    public FrmTransaksi() {
        initComponents();
        koneksi = Koneksi.getKoneksi();
        
        model = new DefaultTableModel();
        tblKeranjang.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Subtotal");
        
        tampilTanggal();
        txtNoFaktur.setText(buatNoFaktur());
        
        txtNoFaktur.setEditable(false);
        txtTanggal.setEditable(false);
        txtNamaBarang.setEditable(false);
        txtHarga.setEditable(false);
        txtTotalBayar.setEditable(false);
        txtKembalian.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoFaktur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang ", "Nama Barang", "Harga ", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);

        jLabel1.setText("MINIMARKET KASIR - TRANSAKSI");

        jLabel2.setText("INFO NOTA");

        jLabel3.setText("Kode Barang  :");

        jLabel4.setText("Nama Barang :");

        jLabel5.setText("Jumlah Beli     :");

        txtKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBarangActionPerformed(evt);
            }
        });

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });

        jLabel6.setText("No. Faktur      :");

        txtNoFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoFakturActionPerformed(evt);
            }
        });

        jLabel7.setText("Tanggal :");

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga    :");

        jLabel9.setText("PEMBAYARAN");

        jLabel10.setText("Total Bayar  :");

        jLabel11.setText("Cash / Qris  :");

        jLabel12.setText("Kembalian   :");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN TRANSAKSI");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBayar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKembalian)))))
                .addGap(0, 145, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtKodeBarang)
                                    .addComponent(txtJumlah)
                                    .addComponent(txtNoFaktur))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTambah)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnSimpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnTambah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (tblKeranjang.getRowCount() == 0 || txtBayar.getText().equals("") || txtKembalian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Transaksi belum lengkap, bre! Selesaikan pembayaran dulu.");
            return;
        }

        String noFaktur = txtNoFaktur.getText();
        String tanggal = txtTanggal.getText();
        String totalBayar = txtTotalBayar.getText();

        try {
            String sqlTransaksi = "INSERT INTO transaksi (no_faktur, tgl_transaksi, id_petugas, total_bayar) VALUES (?, ?, ?, ?)";
            java.sql.PreparedStatement psTransaksi = koneksi.prepareStatement(sqlTransaksi);
                psTransaksi.setString(1, noFaktur);
                psTransaksi.setString(2, tanggal);
                psTransaksi.setInt(3, 1);
                // PERBAIKAN: Menggunakan setInt karena total_bayar bertipe int di database
                psTransaksi.setInt(4, Integer.parseInt(totalBayar)); 
                psTransaksi.executeUpdate();
                
        String sqlDetail = "INSERT INTO detail_transaksi (no_faktur, kode_barang, jumlah, subtotal) VALUES (?, ?, ?, ?)";
         java.sql.PreparedStatement psDetail = koneksi.prepareStatement(sqlDetail);

            int jumlahBaris = tblKeranjang.getRowCount();
              for (int i = 0; i < jumlahBaris; i++) {
                  String kodeBarang = tblKeranjang.getValueAt(i, 0).toString();
                  // Variabel Harga tidak perlu diambil karena tidak disimpan di tabel detail_transaksi database
                  String jumlah      = tblKeranjang.getValueAt(i, 3).toString();
                  String subtotal    = tblKeranjang.getValueAt(i, 4).toString();
               psDetail.setString(1, noFaktur);
               psDetail.setString(2, kodeBarang);
               psDetail.setInt(3, Integer.parseInt(jumlah));    // Menggunakan setInt untuk kolom jumlah
               psDetail.setInt(4, Integer.parseInt(subtotal));  // Menggunakan setInt untuk kolom subtotal
        
               psDetail.executeUpdate();
        }
              

            // Sukses! Kasih notifikasi ke kasir
            JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan ke Database, Bre!");

            // Sesi C: Reset Form biar siap buat transaksi baru
            DefaultTableModel modelKeranjang = (DefaultTableModel) tblKeranjang.getModel();
            modelKeranjang.setRowCount(0); // Kosongkan tabel keranjang
            txtBayar.setText("");
            txtTotalBayar.setText("");
            txtKembalian.setText("");
            
            // Perbarui nomor faktur otomatis biar naik jadi TR0002, TR0003, dst.
            txtNoFaktur.setText(buatNoFaktur()); 
            txtKodeBarang.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
try {
            // 1. Validasi dulu, pastikan kasir udah ngisi kode barang sama jumlah beli
            if (txtKodeBarang.getText().equals("") || txtJumlah.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Silakan pilih barang dan isi Jumlah Beli dulu, bre!");
                return;
            }
            
            // 2. Ambil data angka dari textfield untuk dihitung subtotalnya
            int harga = Integer.parseInt(txtHarga.getText());
            int jumlah = Integer.parseInt(txtJumlah.getText());
            int subtotal = harga * jumlah;
            
            // 3. Masukkan datanya jadi baris baru di tabel keranjang
            model.addRow(new Object[]{
                txtKodeBarang.getText(),
                txtNamaBarang.getText(),
                txtHarga.getText(),
                txtJumlah.getText(),
                subtotal
            });
            
            // 4. Panggil fungsi hitung total belanjaan (kita buat methodnya di bawah)
            hitungTotal();
            
            // 5. Bersihkan kolom inputan barang biar kasir bisa ngetik barang selanjutnya
            txtKodeBarang.setText("");
            txtNamaBarang.setText("");
            txtHarga.setText("");
            txtJumlah.setText("");
            
            // 6. Kembalikan kursor fokus otomatis ke Kode Barang lagi
            txtKodeBarang.requestFocus();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah beli wajib pakai angka valid ya, cuy!");
            txtJumlah.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Eror: " + e.getMessage());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void hitungTotal() {
        int jumlahBaris = tblKeranjang.getRowCount();
        int totalBiaya = 0;
        
        // Melakukan perulangan untuk menjumlahkan semua angka di kolom Subtotal (indeks ke-4)
        for (int i = 0; i < jumlahBaris; i++) {
            totalBiaya += Integer.parseInt(tblKeranjang.getValueAt(i, 4).toString());
        }
        
        // Menampilkan hasil penjumlahan ke kolom Total Bayar di bagian bawah
        txtTotalBayar.setText(String.valueOf(totalBiaya));
    }
    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtNoFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoFakturActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_txtNoFakturActionPerformed

    private void txtKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBarangActionPerformed
        try {
            // 1. Query untuk mencari barang berdasarkan kode yang diketik kasir
            String sql = "SELECT * FROM barang WHERE kode_barang=?";
            java.sql.PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.setString(1, txtKodeBarang.getText());
            java.sql.ResultSet rs = ps.executeQuery();
            
            // 2. Jika barang ditemukan di database
            if (rs.next()) {
                txtNamaBarang.setText(rs.getString("nama_barang")); // Ambil kolom nama_barang
                txtHarga.setText(rs.getString("harga"));           // Ambil kolom harga
                txtJumlah.requestFocus();                          // Kursor otomatis pindah ke Jumlah Beli
            } else {
                // 3. Jika barang tidak ada
                JOptionPane.showMessageDialog(this, "Barang dengan kode tersebut tidak ditemukan!");
                txtKodeBarang.setText("");
                txtNamaBarang.setText("");
                txtHarga.setText("");
                txtKodeBarang.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Eror saat mengambil data barang: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeBarangActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
       try {
            // Query mencari data barang berdasarkan kode yang diketik kasir
            String sql = "SELECT * FROM barang WHERE kode_barang=?";
            java.sql.PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.setString(1, txtKodeBarang.getText());
            java.sql.ResultSet rs = ps.executeQuery();
            
            // Jika barangnya ketemu di database
            if (rs.next()) {
                // Set text ke field nama barang dan harga (sesuai kolom di database kamu)
                txtNamaBarang.setText(rs.getString("nama_barang")); 
                txtHarga.setText(rs.getString("harga"));           
                
                // Kursor otomatis langsung loncat ke kolom Jumlah Beli biar kasir tinggal ngetik angka
                txtJumlah.requestFocus();                          
            } else {
                // Jika kasir asal ngetik kode dan gak ada di database
                JOptionPane.showMessageDialog(this, "Barang dengan kode tersebut tidak ditemukan!");
                txtKodeBarang.setText("");
                txtNamaBarang.setText("");
                txtHarga.setText("");
                txtKodeBarang.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Eror koneksi/query: " + e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        try {
            // 1. Ambil angka dari Total Bayar dan Cash
            int totalBayar = Integer.parseInt(txtTotalBayar.getText());
            int cash = Integer.parseInt(txtBayar.getText()); // Sesuaikan nama variabel txtCash lu
            
            // 2. Validasi kalau uang kasir ternyata kurang
            if (cash < totalBayar) {
                JOptionPane.showMessageDialog(this, "Waduh bre, uang pembayaran kurang!");
                txtKembalian.setText("0");
                return;
            }
            
            // 3. Hitung rumus kembalian
            int kembalian = cash - totalBayar;
            
            // 4. Set hasilnya ke text field kembalian
            txtKembalian.setText(String.valueOf(kembalian)); // Sesuaikan nama variabel txtKembalian lu
            
            // 5. Pindahkan fokus kursor langsung ke tombol SIMPAN TRANSAKSI
            btnSimpan.requestFocus(); // Sesuaikan nama variabel tombol simpan lu
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input nominal uang bayar yang valid dong, cuy!");
            txtBayar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void tampilTanggal() {
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat s = new java.text.SimpleDateFormat("yyyy-MM-dd");
        txtTanggal.setText(s.format(date));
    }
    
    private String buatNoFaktur() {
        try {
            String sql = "SELECT no_faktur FROM transaksi ORDER BY no_faktur DESC LIMIT 1";
            java.sql.Statement st = koneksi.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String noFaktur = rs.getString("no_faktur").substring(2);
                int AN = Integer.parseInt(noFaktur) + 1;
                return "TR" + String.format("%04d", AN);
            } else {
                return "TR0001";
            }
        } catch (Exception e) {
            return "TR0001";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNoFaktur;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
